version: 2

jobs:

  validate:
    docker:
      - image: hashicorp/packer:light

    steps:
      - checkout
      - run:
         name: validate
         command: |
             packer validate gcloud_sdk_packer.json

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - validate
